[package]
name = "bootstrap"
edition = "2018"
version = "0.0.1"
authors = [
    "Brandon Thomas <bt@brand.io>",
    "Brandon Thomas <echelon@gmail.com>",
]
publish = false

[lib]
# NB: Public "bootstrap" crate is real, but doesn't seem useful.
name = "bootstrap"
path = "src/lib.rs"

[package.metadata.cargo-udeps.ignore]
normal = ["workspace-build-acceleration"]

[dependencies]
# Internal
easyenv = { path = "../easyenv" }
errors = { path = "../errors" }
server_environment = { path = "../server_environment" }

# Workspace hack (faster compile times)
workspace-build-acceleration = { version = "0.1", path = "../../workspace-build-acceleration" }

# External
dotenv.workspace = true
hostname.workspace = true
log = "0.4.14"

[dev-dependencies]
tempfile.workspace = true
