import { defineTunables } from "@/lib/tuner";

// Structure knobs — changing these rebuilds the tick track / word layouts
// (consumers subscribe and debounce, same pattern as the hero wall).
export const rulerLayoutTuner = defineTunables("rulerLayout", "Ruler layout", {
  side: {
    label: "Side 0=L 1=R",
    min: 0,
    max: 1,
    step: 1,
    default: 1,
    info: "Which viewport edge the ruler lives on: 0 = left, 1 = right.",
  },
  edgePad: {
    label: "Edge pad px",
    min: 0,
    max: 40,
    step: 2,
    default: 12,
    info: "Vertical inset of the ruler's whole mapping (needle travel, clicks, compact map) from the nav bottom and viewport bottom — keeps the 0/100 ticks and labels fully visible.",
  },
  railW: {
    label: "Rail width px",
    min: 32,
    max: 96,
    step: 2,
    default: 60,
    info: "Width of the tick rail at the viewport edge; also the gutter reserved from page content.",
  },
  minorPct: {
    label: "Tick every %",
    min: 0.5,
    max: 5,
    step: 0.5,
    default: 1,
    info: "Scroll-percent spacing between minor ticks on the rail.",
  },
  labelPct: {
    label: "Label every %",
    min: 5,
    max: 25,
    step: 5,
    default: 5,
    info: "Scroll-percent spacing between the longer, number-labeled major ticks.",
  },
  thresholdPct: {
    label: "Flip line vh%",
    min: 4,
    max: 40,
    step: 1,
    default: 12,
    info: "Viewport-height % from the top where a riding word flips horizontal into the top stack.",
  },
  headingPx: {
    label: "Heading px",
    min: 12,
    max: 34,
    step: 1,
    default: 34,
    info: "Font size of the full-size current-section heading below the top pile.",
  },
  ridingPx: {
    label: "Riding px",
    min: 9,
    max: 24,
    step: 1,
    default: 20,
    info: "Font size of the vertical word riding the rail with its section.",
  },
  queuePx: {
    label: "Queue px",
    min: 9,
    max: 24,
    step: 1,
    default: 16,
    info: "Font size of the compact heading links (bottom queue and top pile).",
  },
  topPad: {
    label: "Top pad px",
    min: 4,
    max: 120,
    step: 4,
    default: 28,
    info: "Gap between the nav bar and the first heading in the top pile.",
  },
  currentGap: {
    label: "Current gap px",
    min: 8,
    max: 80,
    step: 2,
    default: 26,
    info: "Extra gap separating the full-size current heading from the compact pile above it.",
  },
  queueSlot: {
    label: "Queue slot px",
    min: 12,
    max: 48,
    step: 2,
    default: 20,
    info: "Vertical spacing between stacked heading links, top pile and bottom queue alike.",
  },
  queuePad: {
    label: "Queue bottom px",
    min: 8,
    max: 120,
    step: 4,
    default: 36,
    info: "Gap between the viewport bottom and the lowest queued heading.",
  },
  textPad: {
    label: "Text pad px",
    min: 0,
    max: 48,
    step: 2,
    default: 0,
    info: "Horizontal gap between the tick rail and the heading text.",
  },
});

// Feel knobs — read per frame.
export const rulerMotionTuner = defineTunables("rulerMotion", "Ruler motion", {
  flipZone: {
    label: "Flip zone px",
    min: 60,
    max: 600,
    step: 10,
    default: 200,
    info: "Scroll distance over which the vertical-to-horizontal top flip plays out.",
  },
  detachZone: {
    label: "Detach zone px",
    min: 60,
    max: 600,
    step: 10,
    default: 240,
    info: "Scroll distance over which a queued heading morphs onto the rail beside its slot.",
  },
  stagger: {
    label: "Letter stagger",
    min: 0,
    max: 0.3,
    step: 0.01,
    default: 0.16,
    info: "Per-letter delay fraction in flips — higher = letters travel more one-by-one.",
  },
  arc: {
    label: "Curve arc px",
    min: 0,
    max: 200,
    step: 4,
    default: 28,
    info: "How far each letter's flight path bows inward (toward the page) mid-flip.",
  },
  jumpDur: {
    label: "Jump dur s",
    min: 0.2,
    max: 2.5,
    step: 0.05,
    default: 1.25,
    info: "Max duration of a click jump (rail or heading link); short hops scale it down.",
  },
  snapDelay: {
    label: "Snap delay ms",
    min: 100,
    max: 1500,
    step: 50,
    default: 400,
    info: "How long scroll must rest with a flip half-done before it auto-resolves.",
  },
  snapDur: {
    label: "Snap dur s",
    min: 0.2,
    max: 2,
    step: 0.05,
    default: 0.7,
    info: "Duration of the damped auto-scroll that resolves a half-done flip.",
  },
  introDur: {
    label: "Intro dur s",
    min: 0.1,
    max: 2,
    step: 0.05,
    default: 1,
    info: "Draw-in duration of each tick during the page-load cascade.",
  },
  introStagger: {
    label: "Intro stag s",
    min: 0,
    max: 0.02,
    step: 0.001,
    default: 0.01,
    info: "Delay between successive ticks in the load cascade (top-down).",
  },
  velRadius: {
    label: "Vel radius px",
    min: 0,
    max: 500,
    step: 10,
    default: 180,
    info: "Document distance around the needle within which ticks react to scroll speed.",
  },
  velMax: {
    label: "Vel stretch",
    min: 0,
    max: 2,
    step: 0.05,
    default: 0.6,
    info: "How much fast scrolling stretches the ticks nearest the needle.",
  },
  zoomInDelay: {
    label: "Zoom delay ms",
    min: 0,
    max: 800,
    step: 25,
    default: 150,
    info: "Hover intent time on the rail before the full-page zoom engages — accidental edge grazes don't fire.",
  },
  zoomOutDelay: {
    label: "Unzoom delay ms",
    min: 0,
    max: 800,
    step: 25,
    default: 150,
    info: "Grace period after leaving the rail before the zoom relaxes back to 1:1.",
  },
  zoomLerp: {
    label: "Zoom damping",
    min: 2,
    max: 16,
    step: 0.5,
    default: 10,
    info: "Damping rate of the zoom morph — higher = snappier compression onto the needle.",
  },
  dragLerp: {
    label: "Drag lerp",
    min: 0.05,
    max: 0.6,
    step: 0.01,
    default: 0.18,
    info: "How tightly the page chases the cursor while thumb-dragging the zoomed rail.",
  },
  heroLead: {
    label: "Hero lead px",
    min: 0,
    max: 400,
    step: 10,
    default: 100,
    info: "How many scroll px before the wordmark would duck under the nav the hero-to-header morph begins.",
  },
  heroZone: {
    label: "Hero morph px",
    min: 100,
    max: 900,
    step: 20,
    default: 320,
    info: "Scroll distance the hero wordmark's flight to the top heading slot spans.",
  },
});

// Ink knobs — read per frame.
export const rulerLookTuner = defineTunables("rulerLook", "Ruler look", {
  minorAlpha: {
    label: "Minor alpha",
    min: 0,
    max: 1,
    step: 0.05,
    default: 0.4,
    info: "Opacity of the minor ticks.",
  },
  majorAlpha: {
    label: "Major alpha",
    min: 0,
    max: 1,
    step: 0.05,
    default: 0.8,
    info: "Opacity of labeled major ticks and the riding section ticks.",
  },
  labelAlpha: {
    label: "Label alpha",
    min: 0,
    max: 1,
    step: 0.05,
    default: 0.5,
    info: "Opacity of the mono percent numbers and section index labels.",
  },
  minorLen: {
    label: "Minor len px",
    min: 2,
    max: 20,
    step: 1,
    default: 10,
    info: "Length of minor ticks, drawn from the outer edge.",
  },
  majorLen: {
    label: "Major len px",
    min: 4,
    max: 28,
    step: 1,
    default: 20,
    info: "Length of labeled major ticks, drawn from the outer edge.",
  },
  ghostAlpha: {
    label: "Ghost alpha",
    min: 0,
    max: 1,
    step: 0.05,
    default: 1,
    info: "Opacity of the hover ghost line previewing where a rail click will jump.",
  },
  ghostThick: {
    label: "Ghost thick px",
    min: 1,
    max: 8,
    step: 1,
    default: 3,
    info: "Thickness of the hover ghost line.",
  },
  queueAlpha: {
    label: "Queue alpha",
    min: 0,
    max: 1,
    step: 0.05,
    default: 0.35,
    info: "Opacity of the compact heading links (bottom queue and top pile) and of the in-transit riding word — everything that isn't the active top heading.",
  },
  yieldPad: {
    label: "Yield margin px",
    min: 0,
    max: 80,
    step: 2,
    default: 24,
    info: "Distance around a riding word within which the tick percent labels fade out of its way (proximity yield).",
  },
  needleFadePct: {
    label: "Needle fade %",
    min: 0,
    max: 10,
    step: 0.5,
    default: 3,
    info: "Progress percent below which the needle and its readout fade out — the instrument stays quiet at the very top of the page.",
  },
  bracketAlpha: {
    label: "Bracket alpha",
    min: 0,
    max: 0.5,
    step: 0.02,
    default: 0.1,
    info: "Opacity of the shaded bracket marking the visible page span while zoomed.",
  },
  mapAlpha: {
    label: "Map alpha",
    min: 0,
    max: 1,
    step: 0.05,
    default: 0.85,
    info: "Opacity of the section labels in the zoomed full-page map.",
  },
  poolAlpha: {
    label: "Pool alpha",
    min: 0,
    max: 1,
    step: 0.05,
    default: 1,
    info: "Strength of the page-bg contrast pools behind the top stack and the bottom queue (0 = none).",
  },
  frostSolid: {
    label: "Frost solid %",
    min: 0,
    max: 80,
    step: 5,
    default: 40,
    info: "Portion of the rail (from the outer edge) where the frost is at full strength before the feather begins.",
  },
  frostGamma: {
    label: "Frost ease",
    min: 0.5,
    max: 4,
    step: 0.1,
    default: 2.2,
    info: "Falloff curve of the frost's inner feather — higher eases in longer toward the page (a slower, less visible tail).",
  },
  poolPad: {
    label: "Pool pad px",
    min: 0,
    max: 160,
    step: 8,
    default: 64,
    info: "Feather margin the contrast pools extend beyond the top stack's and bottom queue's actual bounding boxes.",
  },
});
