// Every tweakable constant of the hero galaxy, registered with the dev
// tuner (see TUNER.md). Defaults here ARE the shipped values — tune live,
// copy the JSON from the panel, then update the defaults.

import { defineTunables } from "@/lib/tuner";

// Structure knobs — changing these rebuilds the arm paths, tick marks, and
// card roster (debounced).
export const galaxyLayoutTuner = defineTunables(
  "galaxyLayout",
  "Galaxy layout",
  {
    arms: {
      label: "Arms",
      min: 2,
      max: 6,
      step: 1,
      default: 6,
      info: "How many spiral arms emanate from the center; cards are dealt across them round-robin.",
    },
    turns: {
      label: "Turns per arm",
      min: 0.4,
      max: 2.5,
      step: 0.05,
      default: 1.05,
      info: "How many revolutions each arm makes from origin to outer end — lower is straighter rays, higher is a tighter swirl.",
    },
    rMaxFrac: {
      label: "Track pitch",
      min: 0.4,
      max: 1.2,
      step: 0.02,
      default: 0.7,
      info: "Sets the spiral's tightness: the radius the drawn windings span, as a fraction of the viewport half-diagonal. Larger = wider winding gaps = bigger cards. Cards travel past it until fully offscreen.",
    },
    birthFrac: {
      label: "Birth radius",
      min: 0.02,
      max: 0.4,
      step: 0.01,
      default: 0.08,
      info: "Where cards are born, as a fraction of the outer radius — the nebula pocket around the wordmark.",
    },
    cardN: {
      label: "Card count",
      min: 8,
      max: 96,
      step: 1,
      default: 64,
      info: "Cards riding the arms at the reference viewport size; smaller viewports scale this down proportionally (see Tuned @ Mpx).",
    },
    tunedMpx: {
      label: "Tuned @ Mpx",
      min: 0.5,
      max: 12,
      step: 0.1,
      default: 1.65,
      info: "Viewport area (CSS megapixels) the card count was tuned at. Smaller viewports get proportionally fewer cards — never more than the count knob.",
    },
    cardHFrac: {
      label: "Card h cap",
      min: 0.08,
      max: 0.35,
      step: 0.005,
      default: 0.25,
      info: "Absolute card height ceiling as a fraction of the viewport height — the track-gap math sizes cards below this so they never collide.",
    },
    armJitter: {
      label: "Arm desync",
      min: 0,
      max: 0.5,
      step: 0.01,
      default: 0.13,
      info: "Per-arm conveyor phase offset — 0 makes all arms birth cards in lockstep rings, higher desynchronizes them.",
    },
    ticksPerArm: {
      label: "Ticks / arm",
      min: 0,
      max: 40,
      step: 1,
      default: 16,
      info: "Tick marks straddling each arm's outer half in the line underlay (0 = none).",
    },
    circFrac: {
      label: "Constr circle",
      min: 0.2,
      max: 1,
      step: 0.02,
      default: 0.56,
      info: "Radius of the dashed construction circle in the underlay, as a fraction of the outer radius.",
    },
  },
);

// Feel knobs — read per frame.
export const galaxyMotionTuner = defineTunables(
  "galaxyMotion",
  "Galaxy motion",
  {
    idleSpeed: {
      label: "Idle cyc/min",
      min: 0,
      max: 0.8,
      step: 0.01,
      default: 0.57,
      info: "Unattended conveyor speed — full journeys (birth to edge) per minute.",
    },
    scrub: {
      label: "Scrub /1kpx",
      min: 0,
      max: 1,
      step: 0.01,
      default: 0.2,
      info: "Conveyor journeys advanced per 1000px of scroll — scroll-linked and reversible.",
    },
    spinDeg: {
      label: "Spin °/min",
      min: -60,
      max: 60,
      step: 0.5,
      default: -50,
      info: "Slow global rotation of the whole system (arms, ticks, and card paths together); cards themselves stay upright.",
    },
    wobbleAmp: {
      label: "Wobble px",
      min: 0,
      max: 40,
      step: 1,
      default: 6,
      info: "How far cards drift off their exact arm position — the floating-in-space noise. Collision-safe: sizing measures the real wobbled positions.",
    },
    wobbleFreq: {
      label: "Wobble Hz",
      min: 0,
      max: 2,
      step: 0.05,
      default: 0.25,
      info: "Speed of the floating drift.",
    },
    introDur: {
      label: "Wave dur s",
      min: 0.4,
      max: 4,
      step: 0.05,
      default: 4,
      info: "Duration of the intro reveal wave sweeping from the logo past the outer edge. Starts at the master Intro group's Cards beat.",
    },
    rollChunk: {
      label: "Roll chunk",
      min: 0,
      max: 0.5,
      step: 0.01,
      default: 0.12,
      info: "Fraction of the journey cards drift outward during the reveal — they start slightly short of their spread positions and slide the last chunk in as the wave uncovers them. 0 = reveal in place.",
    },
    burstX: {
      label: "Burst ×",
      min: 1,
      max: 8,
      step: 0.1,
      default: 3,
      info: "Conveyor speed multiplier at the start of the intro, easing down to normal — the field arrives moving and settles into its drift.",
    },
    burstDur: {
      label: "Burst ease s",
      min: 0.5,
      max: 6,
      step: 0.1,
      default: 2.5,
      info: "How long the speed burst takes to ease back to normal conveyor speed.",
    },
    waveBand: {
      label: "Wave band px",
      min: 40,
      max: 600,
      step: 10,
      default: 220,
      info: "Thickness of the reveal wave's front — the zone where a card fades in and racks from blur to focus.",
    },
    waveAber: {
      label: "Wave flare",
      min: 0,
      max: 0.3,
      step: 0.002,
      default: 0.2,
      info: "Dispersion flare of the chromatic ring trailing the reveal wave — cards flash as it crosses them.",
    },
    waveLag: {
      label: "Flare lag s",
      min: 0,
      max: 1,
      step: 0.05,
      default: 0.4,
      info: "How far behind the reveal front the dispersion ring launches — it sweeps the already-revealed field as a second pass.",
    },
    perfFloor: {
      label: "FPS floor",
      min: 0,
      max: 60,
      step: 5,
      default: 30,
      info: "When sustained frame rate drops below this, the galaxy sheds cards (and their decoders) until smooth, then slowly regrows. 0 disables the governor.",
    },
  },
);

// Pointer interaction knobs — read per frame.
export const galaxyPointerTuner = defineTunables(
  "galaxyPointer",
  "Galaxy pointer",
  {
    fieldPx: {
      label: "Field px",
      min: 80,
      max: 800,
      step: 10,
      default: 320,
      info: "Radius of the cursor's influence — cards inside it tilt toward the pointer and pick up dispersion flare.",
    },
    tiltDeg: {
      label: "Tilt °",
      min: 0,
      max: 25,
      step: 0.5,
      default: 0,
      info: "Maximum lean of a card toward the cursor at the field's center — the pulled-at feel. The targeted card straightens to zero.",
    },
    tugPx: {
      label: "Tug px",
      min: 0,
      max: 40,
      step: 1,
      default: 8,
      info: "How far cards inside the field are actually displaced toward the cursor — the translation pull. Collision-safe: sizing measures the tugged positions.",
    },
    mouseWarp: {
      label: "Mouse warp px",
      min: 0,
      max: 400,
      step: 1,
      default: 200,
      info: "The cursor's weight on nearby card surfaces: a local bulge toward the camera at the point of the card nearest the mouse, on top of the base curve warp.",
    },
    flareAdd: {
      label: "Flare add",
      min: 0,
      max: 0.08,
      step: 0.002,
      default: 0.032,
      info: "Extra chromatic dispersion picked up by cards the cursor sweeps near, on top of the base aberration.",
    },
    flareDecay: {
      label: "Flare decay /s",
      min: 0.5,
      max: 8,
      step: 0.1,
      default: 3,
      info: "How fast the sweep flare fades behind the cursor — lower leaves a longer lens trail.",
    },
    holdTau: {
      label: "Hold tau s",
      min: 0.05,
      max: 1,
      step: 0.05,
      default: 0.15,
      info: "How quickly the targeted card's conveyor motion brakes to a stop under the cursor.",
    },
    restTau: {
      label: "Rest tau s",
      min: 0.1,
      max: 4,
      step: 0.05,
      default: 1,
      info: "How quickly the rest of the spiral follows the target to a stop — deliberately slower, so the hold reads as spreading outward from the hand.",
    },
    holdWobble: {
      label: "Hold wobble ×",
      min: 1,
      max: 3,
      step: 0.1,
      default: 1.2,
      info: "Wobble multiplier on the rest of the spiral while a card is held — the flow strains gently against the freeze.",
    },
    targetTau: {
      label: "Target tau s",
      min: 0.05,
      max: 12,
      step: 0.05,
      default: 0.25,
      info: "Behavioral ease of the target lock (sizing pin, paint order, decode priority, wobble kill). The optical clear — dispersion, blur, warp, wash — always runs at a fixed fast pace regardless.",
    },
    rippleSpeed: {
      label: "Ripple px/s",
      min: 200,
      max: 3000,
      step: 50,
      default: 900,
      info: "Expansion speed of a click's dispersion ring.",
    },
    rippleWidth: {
      label: "Ripple width",
      min: 40,
      max: 400,
      step: 10,
      default: 140,
      info: "Thickness of the ripple's dispersion band.",
    },
    rippleAmp: {
      label: "Ripple amp",
      min: 0,
      max: 0.1,
      step: 0.002,
      default: 0.016,
      info: "Peak dispersion the ripple adds to cards it crosses. Multiple clicks stack.",
    },
    rippleWarp: {
      label: "Ripple warp px",
      min: 0,
      max: 80,
      step: 1,
      default: 22,
      info: "How far a card's surface pops toward the camera as the ripple ring passes through it — the physical half of the click feedback.",
    },
    rippleLife: {
      label: "Ripple life s",
      min: 0.4,
      max: 4,
      step: 0.1,
      default: 1.8,
      info: "How long a ripple keeps its strength as it travels before fading out.",
    },
    clickAmp: {
      label: "Punch amp px",
      min: 0,
      max: 30,
      step: 1,
      default: 20,
      info: "Peak texture displacement of the local click punch — the circular wave that grows from the click point across the clicked card only. Clicks stack.",
    },
    clickDur: {
      label: "Punch dur s",
      min: 0.2,
      max: 1.5,
      step: 0.05,
      default: 0.75,
      info: "Time for the punch ring to travel from the click point to the card edges and die.",
    },
    clickWidth: {
      label: "Punch width",
      min: 0.04,
      max: 0.4,
      step: 0.01,
      default: 0.14,
      info: "Thickness of the punch ring as a fraction of the card size — the softness of the blurred circle driving the displacement.",
    },
    boostScale: {
      label: "Boost scale ×",
      min: 1.2,
      max: 3,
      step: 0.1,
      default: 2,
      info: "Scale multiplier a click toggles onto the held card. Allowed to overlap neighbors; scales back down on leaving the card, and the next hold needs a fresh click.",
    },
    boostTau: {
      label: "Boost tau s",
      min: 0.05,
      max: 0.6,
      step: 0.01,
      default: 0.18,
      info: "Ease time of the click-boost scale, up and down.",
    },
  },
);

// Ink and lens knobs — read per frame.
export const galaxyLookTuner = defineTunables("galaxyLook", "Galaxy look", {
  density: {
    label: "Density",
    min: 0.3,
    max: 1,
    step: 0.02,
    default: 0.82,
    info: "Fraction of the gap to its nearest neighbor each card may fill — higher packs the screen tighter, lower gives more air. Collision-free across the whole range (at 1.0 cards may kiss edges).",
  },
  cornerPx: {
    label: "Corner px",
    min: 0,
    max: 24,
    step: 1,
    default: 10,
    info: "Corner radius of each card (and its hairline frame), in px — the one deliberate exception to the site's zero-radius rule.",
  },
  innerCap: {
    label: "Inner cap",
    min: 0.2,
    max: 1,
    step: 0.02,
    default: 0.45,
    info: "Size ceiling for newborn cards as a fraction of the full cap, ramping up over the journey — keeps inner cards smaller than outer ones even when space would allow more.",
  },
  aspectEnd: {
    label: "Square until",
    min: 0.05,
    max: 0.8,
    step: 0.01,
    default: 0.3,
    info: "Journey fraction over which a newborn card morphs from a rounded square into its full 16:9 aspect.",
  },
  blurMax: {
    label: "Blur max",
    min: 0,
    max: 0.25,
    step: 0.005,
    default: 0.12,
    info: "Blur radius (in card-UV units) at birth — the nebula softness at the center; also the blur a still-loading card holds.",
  },
  blurEnd: {
    label: "Blur end",
    min: 0.05,
    max: 0.9,
    step: 0.01,
    default: 0.18,
    info: "Journey fraction where the blur fully resolves to sharp.",
  },
  playFrac: {
    label: "Play from",
    min: 0,
    max: 1,
    step: 0.02,
    default: 0.14,
    info: "Journey fraction past which a card's clip earns a live decoder — inner blurred cards hold a frozen frame.",
  },
  fadeBand: {
    label: "Birth fade",
    min: 0.02,
    max: 0.3,
    step: 0.01,
    default: 0.15,
    info: "Fraction of the journey over which a newborn card fades in at the center. There is no exit fade — cards die fully offscreen.",
  },
  aberration: {
    label: "Dispersion",
    min: 0,
    max: 0.06,
    step: 0.001,
    default: 0.019,
    info: "Chromatic aberration strength toward each card's edges — the cheap lens-dispersion detail.",
  },
  curvePx: {
    label: "Curve px",
    min: 0,
    max: 160,
    step: 1,
    default: 32,
    info: "How far each card's center bows toward the camera — the slight lens-warp of the plane.",
  },
  frameAlpha: {
    label: "Frame alpha",
    min: 0,
    max: 1,
    step: 0.02,
    default: 0.22,
    info: "Strength of the hairline frame drawn along each card's (rounded) edge.",
  },
  lineAlpha: {
    label: "Line alpha",
    min: 0,
    max: 1,
    step: 0.02,
    default: 0.15,
    info: "Opacity of the arm guide curves and construction circle in the underlay — 0 kills the geometric layer entirely.",
  },
  tickAlpha: {
    label: "Tick alpha",
    min: 0,
    max: 1,
    step: 0.02,
    default: 0.3,
    info: "Opacity of the tick marks along the arms.",
  },
});
